//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TS15V2.UI.APP.dev.GestionTransformador {
    
    
    public partial class BusquedaTransformador {
        
        /// <summary>
        /// ucBusquedaCliente control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TS15.UI.APP.componentes.BuscarCliente ucBusquedaCliente;
        
        /// <summary>
        /// ucBusquedaTransformador control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TS15V2.UI.APP.componentes.BuscarTransformador ucBusquedaTransformador;
    }
}
