//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TS15.UI.APP.systems.Gestion_Cliente
{


    public partial class Detalle_Pedido
    {
    }
}
