///////////////////////////////////////////////////////////
//  IGestionable.cs
//  Implementation of the Interface IGestionable
//  Generated by Enterprise Architect
//  Created on:      14-abr.-2015 10:08:07 a. m.
//  Original author: asuspc
///////////////////////////////////////////////////////////




namespace TS15V2.UI.APP.abstractUI
{
	public interface IGestionable  {

		void Crear();

		void Eliminar();

		void Modificar();

		void Guardar();

		void Cancelar();
	}//end IGestionable

}//end namespace abstracUI