///////////////////////////////////////////////////////////
//  ITerminable.cs
//  Implementation of the Interface ITerminable
//  Generated by Enterprise Architect
//  Created on:      14-abr.-2015 10:08:18 a. m.
//  Original author: william_cuadros
///////////////////////////////////////////////////////////




using System;
namespace TS15V2.UI.APP.abstractUI
{
	public interface ITerminable  {

        void Terminar(object sender, EventArgs e);
	}//end ITerminable

}//end namespace abstracUI