///////////////////////////////////////////////////////////
//  DAOProtocolo_NTC1465.cs
//  Implementation of the Class DAOProtocolo_NTC1465
//  Generated by Enterprise Architect
//  Created on:      25-abr.-2015 11:08:10 a. m.
//  Original author: william_cuadros
///////////////////////////////////////////////////////////




using TS15.Common.Generated;
using TS15.Common.IService;
using TS15.DAL.abstractDAL;
using System.Data.Objects.DataClasses;
using System.Collections.Generic;
namespace TS15.DAL.gestion_protocolo {
	public class DAOProtocoloNTC1465 : DAOGenerico, IGestionable, IProbable {

        public DAOProtocoloNTC1465(){

		}

		/// <summary>
		/// Esta función desbloquea los campos del formulario y habilita los botones.
		/// </summary>
		/// <param name="entidad"></param>
		public bool Modificar(EntityObject entidad){

			return false;
		}

		/// 
		/// <param name="entidad"></param>
		public bool Terminar(EntityObject entidad){

			return false;
		}

		public List<EntityObject> Consultar(){

			return null;
		}

		/// 
		/// <param name="prueba"></param>
		public EntityObject ObtenerUltimaPrueba(tfr_transformador prueba){

			return null;
		}

		/// 
		/// <param name="id"></param>
		public EntityObject ConsultarXId(int id){

			return null;
		}

		/// 
		/// <param name="entidad"></param>
		public bool Crear(EntityObject entidad){

			return false;
		}

		/// 
		/// <param name="entidad"></param>
		public bool Eliminar(EntityObject entidad){

			return false;
		}

	}//end DAOProtocolo_NTC1465

}//end namespace gestion_protocolo