///////////////////////////////////////////////////////////
//  UtilNumeros.cs
//  Implementation of the Class UtilNumeros
//  Generated by Enterprise Architect
//  Created on:      22-abr.-2015 11:08:44 a. m.
//  Original author: william_cuadros
///////////////////////////////////////////////////////////




using System;
namespace util {
	public static class UtilNumeros {

		/// <summary>
		/// Permite convertir una cadena de caracteres a decimal.
		/// </summary>
		public static decimal StringToDecimal(string valor){

            decimal _valor;
            Decimal.TryParse(valor, out _valor);

            return _valor;
		}

        /// <summary>
        /// Permite convertir una cadena de caracteres a byte. 
        /// </summary>
        /// <param name="valor">cadena debe contener un valor entre 0 - 255</param>
        /// <returns>representación el valor en bytes</returns>
        public static byte StringToBytes(string valor)
        {
            try
            {
                int intValor = int.Parse(valor);
                byte bytesValor = (byte)intValor;
                return bytesValor;
            }
            catch (FormatException e)
            {
                return 0;
            }
        }

	}//end UtilNumeros

}//end namespace util