///////////////////////////////////////////////////////////
//  UtilNumeros.cs
//  Implementation of the Class UtilNumeros
//  Generated by Enterprise Architect
//  Created on:      22-abr.-2015 11:08:44 a. m.
//  Original author: william_cuadros
///////////////////////////////////////////////////////////




using System;
namespace util {
	public static class UtilNumeros {

		/// <summary>
		/// Permite convertir una cadena de caracteres a decimal.
		/// </summary>
		public static decimal StringToDecimal(string valor){

            decimal _valor;
            Decimal.TryParse(valor, out _valor);

            return _valor;
		}

	}//end UtilNumeros

}//end namespace util