///////////////////////////////////////////////////////////
//  BOProtocolo_NTC471.cs
//  Implementation of the Class BOProtocolo_NTC471
//  Generated by Enterprise Architect
//  Created on:      25-abr.-2015 11:08:37 a. m.
//  Original author: william_cuadros
///////////////////////////////////////////////////////////

using TS15.Common.Generated;
using TS15.BL.abstractBL;
using TS15.Common.IService;
using TS15.DAL.gestion_protocolo;
using System.Data.Objects.DataClasses;
using System.Collections.Generic;

namespace TS15.BL.gestion_protocolo
{
    public class BOProtocolo_NTC471 : BOGenerico, IGestionable, IProbable
    {
        private DAOProtocolo_NTC471Detalle _DAOntc471Object;

        public BOProtocolo_NTC471()
        {
            GenericoDAO = new DAOProtocolo_NTC471();
            _DAOntc471Object = new DAOProtocolo_NTC471Detalle();
        }

        public bool Modificar(pro_ntc471 prueba, List<pro_ntc471_has_relacion> listaDetalle)
        {
            if (Modificar(prueba))
            {
                if(_DAOntc471Object.Modificar(listaDetalle) != true)
                    return false;
            }
            return true;
        }

        /// <summary>
        /// Esta función desbloquea los campos del formulario y habilita los botones.
        /// </summary>
        /// <param name="entidad"></param>
        public bool Modificar(EntityObject entidad)
        {
            return ((DAOProtocolo_NTC471)GenericoDAO).Modificar(entidad);
        }

        /// 
        /// <param name="entidad"></param>
        public bool Terminar(EntityObject entidad)
        {

            return ((DAOProtocolo_NTC471)GenericoDAO).Terminar(entidad);
        }

        public List<EntityObject> Consultar()
        {

            return null;
        }

        public object[] ObtenerUltimaPruebaDetalle(tfr_transformador transformador)
        {
            object[] pruebaDetalle = new object[2];
            pro_ntc471 prueba = ObtenerUltimaPrueba(transformador) as pro_ntc471;

            if (prueba != null)
            {
                pruebaDetalle[0] = prueba;
                List<pro_ntc471_has_relacion> listDetalle = _DAOntc471Object.ConsultarListaXIdPrueba(prueba.id);

                if (listDetalle != null)
                {
                    pruebaDetalle[1] = listDetalle;
                    return pruebaDetalle;
                }
            }

            return null;
        }

        public object[] ObtenerPruebaDetalle(pro_ntc471 prueba) {
            object[] pruebaDetalle = new object[2];
            
            if (prueba != null)
            {
                pruebaDetalle[0] = prueba;
                List<pro_ntc471_has_relacion> listDetalle = _DAOntc471Object.ConsultarListaXIdPrueba(prueba.id);

                if (listDetalle != null)
                {
                    pruebaDetalle[1] = listDetalle;
                    return pruebaDetalle;
                }
            }

            return null;
        }

        /// 
        /// <param name="prueba"></param>
        public EntityObject ObtenerUltimaPrueba(tfr_transformador transformador)
        {
            return ((DAOProtocolo_NTC471)GenericoDAO).ObtenerUltimaPrueba(transformador);
        }

        /// 
        /// <param name="id"></param>
        public EntityObject ConsultarXId(int id)
        {

            return null;
        }

        /// 
        /// <param name="entidad"></param>
        public bool Crear(EntityObject entidad)
        {

            return false;
        }

        /// 
        /// <param name="entidad"></param>
        public bool Eliminar(EntityObject entidad)
        {

            return false;
        }

        public pro_elementoprueba ObternerPruebasXProceso(int proceso)
        {
            return ((DAOProtocolo_NTC471)GenericoDAO).ObternerPruebasXProceso(proceso);
        }
    }//end BOProtocolo_NTC1465

}//end namespace gestion_protocolo